version: '3'

services:

  imob_users-db:
    image: mongo:latest
    container_name: imob_users-db
    networks:
      - valeimoveis
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017

  logging-db:
    image: mongo:latest
    container_name: logging-db
    networks:
      - valeimoveis
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27018:27017

  customer_visit-db:
    image: postgres:latest
    container_name: customer_visit-db
    networks:
      - valeimoveis
    environment:
      - POSTGRES_DB=customer_visit-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

  real_estate-db:
    image: postgres:latest
    container_name: real_estate-db
    networks:
      - valeimoveis
    environment:
      - POSTGRES_DB=real_estate-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

  wait_list-db:
    image: postgres:latest
    container_name: wait_list-db
    networks:
      - valeimoveis
    environment:
      - POSTGRES_DB=wait_list-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - valeimoveis
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - valeimoveis
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  vib-apigateway:
    build: './vib-apigateway'
    container_name: vib-apigateway
    depends_on:
      - kafka
    networks:
      - valeimoveis
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "3000:3000"

  vib-customervisit:
    build: './vib-customervisit'
    container_name: vib-customervisit
    depends_on:
      - kafka
      - customer_visit-db
    networks:
      - valeimoveis
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=customer_visit-db
      - DB_NAME=customer_visit-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8090:8090"

  vib-realestate:
    build: './vib-realestate'
    container_name: vib-realestate
    depends_on:
      - kafka
      - real_estate-db
    networks:
      - valeimoveis
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=real_estate-db
      - DB_NAME=real_estate-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8091:8091"

  vib-user:
    build: './vib-user'
    container_name: vib-user
    depends_on:
      - kafka
      - imob_users-db
    networks:
      - valeimoveis
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@imob_users-db:27017
    ports:
      - "8092:8092"

  vib-waitlist:
    build: './vib-waitlist'
    container_name: vib-waitlist
    depends_on:
      - kafka
      - wait_list-db
    networks:
      - valeimoveis
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=wait_list-db
      - DB_NAME=wait_list-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8093:8093"

  vib-logging:
    build: './vib-logging'
    container_name: vib-logging
    depends_on:
      - kafka
      - logging-db
    networks:
      - valeimoveis
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@logging-db:27017
    ports:
      - "8094:8094"


networks:
  valeimoveis:
    driver: bridge