server:
  port: 8094
  include-stacktrace: never

spring:
  application:
    name: vib-logging

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: valeimoveis
      auto-offset-reset: latest

  datasource:
    mongodb:
      database: logging-db
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27018}

  logging:
    level:
      org:
        apache:
          kafka: INFO

