spring:
  application:
    name: vib-user

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: valeimoveis
      auto-offset-reset: latest

  data:
    mongodb:
      database: valeimoveisadmin
      uri: ${MONGO_DB_URI:mongodb://valeimoveisadmin:123456@localhost:27017}

  logging:
    level:
      org:
        apache:
          kafka: INFO

