server:
  port: 3000
  include-stacktrace: never

spring:
  application:
    name: vib-apigateway

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: valeimoveis
      auto-offset-reset: latest

  logging:
    level:
      org:
        apache:
          kafka: INFO

